### ISSUE TITLE
Use mqtt sub-pub model for message callback

### ISSUE THREAD

**Issue by vzhr** [shupx/swarm_ros_bridge#7]
In this project, we  receive messages by loop on a high frequency, so that it maybe a little expensive. I have found that mqtt has sub-pub model, does this will help?
https://zeromq.org/socket-api/?language=cpp&library=zmqpp#Publish-subscribe%20pattern

**Comment by shupx** [comment]
Thanks for your attention. But in this project, messages are handled once new message coming rather than in a high frequency loop. I did tried to receive messages in a loop but commented these lines out.
btw, this project uses the zeroMQ pub/sub mode as the link you attached.

**Comment by shupx** [comment]
https://github.com/shupx/swarm_ros_bridge/blob/3b3729066d0fdaa8a45283dcf4696dc72b36e46b/src/bridge_node.cpp#L122

Notixe that 'dont_block' is set false which leads to block in receiving threads until new messages coming

**Comment by vzhr** [comment]
OK, Good job.
